### ISSUE TITLE
any update?

### ISSUE THREAD

**Issue by notedit** [chetanbnaik/wrtclient#2]

**Comment by chetanbnaik** [comment]
yes, the release is working...

**Comment by chetanbnaik** [comment]
hi, the code is complete. It can now act as a native webrtc client. There is an increased dependency though on gstreamer. I have to write the install instruction and tidy the code a bit. meanwhile, you can refer to [wrtclient/instructions](https://raw.githubusercontent.com/chetanbnaik/wrtclient/master/instructions)

**Comment by notedit** [comment]
ok  thanks    i will try this later
